from __future__ import annotations


SCHEMA_VERSION = "2"

STATUSES = {
    "NEW",
    "ANALYZING",
    "AWAITING_HUMAN",
    "READY",
    "RUNNING",
    "BLOCKED",
    "FAILED",
    "VERIFIED",
    "COMPLETED",
    "CANCELLED",
}

PROFILES = {"LEAN", "STANDARD", "DEEP"}

STAGES = [
    "INGEST",
    "DOCUMENT_ANALYSIS",
    "REQUIREMENT_ANALYSIS",
    "MEMORY_RETRIEVAL",
    "DOMAIN_RETRIEVAL",
    "BLIND_SPOT",
    "GATE_A0",
    "SKILL_SELECTION",
    "PLANNING",
    "GATE_A",
    "IMPLEMENTATION",
    "TESTING",
    "REVIEW",
    "VERIFICATION",
    "GATE_C",
    "MEMORY_CURATION",
    "HANDOFF",
    "GATE_D",
    "COMPLETE",
]

ARTIFACT_TYPES = {
    "REQUIREMENT",
    "DOCUMENT_MANIFEST",
    "DOCUMENT_INTELLIGENCE",
    "MEMORY_BRIEF",
    "DOMAIN_CONTEXT",
    "BLIND_SPOT_REPORT",
    "SKILL_SELECTION",
    "PLAN",
    "IMPLEMENTATION_SUMMARY",
    "TEST_EVIDENCE",
    "REVIEW_REPORT",
    "VERIFICATION_REPORT",
    "DECISION",
    "KNOWLEDGE",
    "HANDOFF",
    "TRACEABILITY",
    "AGENT_RUN_STATE",
    "DOCUMENT_REVIEW",
    "DOCUMENT_PROMOTION",
    "AI_CORE_SUMMARY",
}

GATES = {"A0", "A", "C", "D"}

INPUT_TYPES = {"STRUCTURED_REQUIREMENT", "SOURCE_DOCUMENT"}
